import ReduxProvider from '@/components/ReduxProvider/ReduxProvider'
import ModalWrapper from '@/components/ModalWrapper/ModalWrapper'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'АБПЗ Лаб1',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="uk">
            <body className={`bg-cyan-950 text-white ${inter.className}`}>
                <ReduxProvider>
                    {children}
                    <ModalWrapper />
                </ReduxProvider>
            </body>
        </html>
    )
}
